language: objective-c

script:
- xctool -project Login_Demo.xcodeproj -scheme Login_Demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

- xctool test -project Login_Demo.xcodeproj -scheme Login_DemoTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
